#!/bin/bash
####################################################
#### CONFIGURATION FILES ON LOCAL SERVER
####################################################
#
# Location of the sanger script
SANGER_SCRIPT="/opt/sanger_script/sanger_script.sh"
#
# Directory where the processed items will be located
PROCESSED_FILE_DIRECTORY="/opt/sanger_script"
#
# File name for the processed runs
PROCESSED_FILE_NAME="logs/run_processed"
#
# Path of the mounted samba folder
PATH_SANGER_FOLDER="/srv/sanger"
#
# TEMPORARY DIRECTORY WHERE SHARED CONFIGURATION FILE ARE SAVED BEFORE COPYING TO REMOTE SERVER
TMP_SAMBA_SHARE_DIR=/opt/sanger_script/tmp/shares
#
# LOCATION OF THE TEMPLATE FILE FOR CONFIG SAMBA SHARED FOLDERS
SAMBA_SHARE_TEMPLATE=/opt/sanger_script/template.conf
#
# FOLDER TO KEEP TRACK OF THE SHARED FOLDER FOR REMOVING AFTER RETENTION PERIOD
SAMBA_TRANSFERED_FOLDERS=/opt/sanger_script/transfered_folder/
#
# LOCATION OF THE TEMPLATE FILE FOR SENDING EMAILS
TEMPLATE_EMAIL=/opt/sanger_script/template_mail.htm
#

####################################################
#### CONFIGURATION FILES ON REMOTE SERVER
####################################################
#
# DIRECTORY ON THE REMOTE SERVER, WHERE THE SHARED FILES WILL BE COPY
REMOTE_SAMBA_SHARE_DIR=/etc/samba/smb.conf.d
#
# Remote Folder where to put the shared files
REMOTE_SAMBA_SHARED_FOLDER="/srv/genomica/sanger_users"
REMOTE_SAMBA_SANGER_FOLDER="/srv/genomica/sanger"
#
# USER USED FOR REMOTE LOGIN
#REMOTE_USER="genomicadm"
REMOTE_USER="bioinfocifs"
#
# REMOTE SERVER WHERE TO COPY THE OUTPUT FILES
#REMOTE_SAMBA_SERVER="neptuno"
REMOTE_SAMBA_SERVER="barbarroja"

####################################################
########## Configuration settings for deleting old folders ########
####################################################
# Without the + or -, already included in the scripts.
#RETENTION_TIME_SHARED_FOLDERS="182"
RETENTION_TIME_SHARED_FOLDERS="60"
#RETENTION_TIME_CONF_FILES="21"
RETENTION_TIME_CONF_FILES="15"
#
